# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nivaldoandrade
# "service" is the name of this project. This will also be added to your AWS resource names.
service: api

provider:
  name: aws
  runtime: nodejs24.x
  memorySize: 128
  architecture: arm64
  region: sa-east-1
  httpApi:
    cors: true
  environment:
    FILE_BUCKET_NAME: !Ref FileBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:ListBucketMultipartUploads
            - s3:AbortMultipartUpload
          Resource:
            - !Sub ${FileBucket.Arn}/*
            - !GetAtt FileBucket.Arn



package:
  individually: true


build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'
    external:
      - '@aws-sdk/*'

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${sls:stage}-file-bucket
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
              AllowedOrigins:
                - 'http://localhost:5173'
              ExposedHeaders:
                - 'Etag'
        LifecycleConfiguration:
          Rules:
            - Id: ExpireIncompleteMultipartUploadIn1Day
              Status: Enabled
              AbortIncompleteMultipartUpload:
                DaysAfterInitiation: 1 #1day

functions:
  createMPU:
    handler: src/functions/createMPU.handler
    events:
      - httpApi:
          path: /create-mpu
          method: post
  completeMPU:
    handler: src/functions/completeMPU.handler
    events:
      - httpApi:
          path: /complete-mpu
          method: post
  listMPUs:
    handler: src/functions/listMPUs.handler
    events:
      - httpApi:
          path: /list-mpus
          method: get
  abortAllMPUs:
    handler: src/functions/abortAllMPUs.handler
    events:
      - httpApi:
          path: /abort-all-mpus
          method: delete
  abortMPU:
    handler: src/functions/abortMPU.handler
    events:
      - httpApi:
          path: /abort-mpu
          method: delete

